Ninja-Squad/ninja-squad.github.com

- _config.yml
Try to fix #126 
No changes spotted with the other highlighter...
> change highlighter to pygments

- _includes/themes/twitter/page.html
- _includes/themes/twitter/post.html
- archive.html
- index.html
- tags.html
> Navigation in right panel (archive, tags), with better titles.

- _posts/2015-03-17-quizzie-ops.md
DO NOT MERGE until Tuesday. Note that I'll be in the middle of the Red Sea, so I won't be able to merge it.
Feel free to make changes if you feel it's needed.
> add a post on what we learned regarding ops

- .gitignore
- _posts/2015-05-28-angularjs-promises.md
Do not merge. To publish on 2015-05-28 (Thusday).
> post about angular promises (1/2)

- _posts/2015-05-28-angularjs-promises.md
- _posts/2015-06-04-angularjs-promises-2.md
Do not merge. This one is scheduled for thursday 2015-06-04 (one week after the first one).
> second post about angularjs promises

- _includes/ninjasquad/promotion
Not sure if this is a good thing, but it could be SEO-nice to mention AngularJS 1.4.
> feat(promo): AngularJS ebook promotion with 1.4 mention

- _posts/2015-08-28-rentree-2015.md
Ajout d'une description (en meta pour le SEO).
Ajout de l'année sur les dates (SEO again).
Remplacement des liens internes dans le blog en relatifs (ça c'est juste pour enculer les mouches)
Et ajout de ma passion pour les `&nbsp;`.
Et une modification stylistique mineure.
Cette PR est mergeable par @acrepet si les modifications lui conviennent, car elle targette sa branche, pas master : le post ne sera donc pas publié quand cette PR sera mergé, mais uniquement quand sa PR originelle #147 le sera.
> Training post: @clacote review

- _posts/2015-10-06-es6-part-1.md
After the tedious work of porting the asciidoc to amrkdown, here it is:
the first blog post for the Angular 2 serie "The road to Angular 2".
This is the first part of the ES6 chapter, pretty much as is.
I added a few sentences, that I'll submit as a PR to the ebook repo.
> post: ng2 - es6 part 1

- _posts/2015-10-27-angular-connect.md
This is a summary of the conference videos I've watched. I still have some left so maybe I'll add a few things.
I think it could be a good blog post, and a good email to our ML.
> post: angular connect

- _posts/2014-12-15-what-is-coming-in-angularjs-1.4.md
The article I wrote as a preview is weirdly popular and well referenced, 
so it doesn't hurt to redirect to the more recent and accurate one.
> update: redirect to a more recetn article for ng1.4

- _posts/2015-11-17-typescript-part-2.md
This is the post for next tuesday: TS part 2.
I rewrote the decorator part and added a few things.
If you find it OK, I'll push a PR for the book with the same stuff.
> post: typescript part 2

- .gitignore
- _posts/2016-02-14-cadendrier-formations-debut2016.md
New trainings calendar. About Git Training : why not plan a new training session in Lyon?
> new post new trainings calendar

- _config.yml
> fix(trainings) ng2, remove July, push Sept two weeks later

- _posts/2013-08-30-git-rerere-ma-commande-preferee.md
- _posts/2013-09-30-git-config.md
- _posts/2013-12-19-angular-express-socketio.md
- _posts/2014-02-11-workflow-pull-requests-and-code-reviews.md
- _posts/2014-06-24-nouveautes-angularjs-1.3.md
- _posts/2014-07-31-nouveautes-angularjs-1.3-part-2.md
- _posts/2014-08-28-nouveautes-angularjs-1.3-part-3.md
- _posts/2014-10-28-nouveautes-angularjs-1.3-part-4.md
- _posts/2015-03-11-quizzie-spring.md
- _posts/2015-07-21-what-is-new-angularjs-1.4.md
That will help if we change one day to TLS.
> fix(post): remove domain and protocol in internal links

- _posts/2016-11-17-what-is-new-angular-2.2.md
Plan for Thursday, if someone has time to review it.
> post: what's new in angular 2.2

- _posts/2017-07-03-what-is-new-angular-4.3.md
Waiting for the official 4.3 release which was planned for today, but will probably be later this month (no RC released yet).
> post: what's new in ng 4.3

- _posts/2017-08-10-angular-cli-1.3.md
- _posts/2017-09-14-angular-cli-1.4.md
This is planned for thursday to give you time to review
> post: angular cli 1.4

- _posts/2017-09-18-what-is-new-angular-4.4.md
Angular 4.4 dropped yesterday. Not much to say about it, but I wrote about it anyway.
Release target is Monday morning if you have time to review it, but we can publish later if you can't.
> post: ng 4.4

- _posts/2017-08-17-what-is-new-angular-5.md
- _posts/2017-11-02-what-is-new-angular-5.md
> post: ng 5

- _posts/2017-10-24-angular-cli-1.5.md
- _posts/2017-11-03-angular-cli-1.5.md
WIP: you don't have to review right now
The CLI will probably come out after ng 5 (there are still some outstanding issues not fixed).
> post: cli 1.5

- _posts/2017-12-07-what-is-new-angular-5.1.md
- _posts/2017-12-18-what-is-new-angular-5.1.md
> post: ng 5.1

- _posts/2017-12-07-what-is-new-angular-5.1.md
> Fix post what's new 5.1

- _posts/2017-04-28-what-is-new-angular-4.1.md
- _posts/2018-01-07-what-is-new-angular-5.2.md
- _posts/2018-01-11-what-is-new-angular-5.2.md
WIP (you don't have to review now)
> post: ng 5.2

- _posts/2018-02-07-angular-cli-1.7.md
- _posts/2018-02-19-angular-cli-1.7.md
WIP (you don't have to review right now)
> post: cli 1.7

- _config.yml
> chore: training dates Q2 2018

- _includes/JB/comments-providers/disqus
- _includes/themes/twitter/post.html
- index.html
Avoid "mixed content" error on https.
> chore(https): reference external assets (gravatar, disqus) with protocol-agnostic urls

- _posts/2018-05-22-kotlin-migration.md
> add post about Kotlin migration

- _posts/2018-06-19-ngx-valdemort.md
- assets/images/ngx-valdemort.svg
> post: ngx-valdemort

- _includes/JB/tags_list
- assets/themes/twitter/css/style.css
Hopefully this will fix the "Too close clickable elements"
> fix: more margin between tags

- assets/themes/twitter/css/style.css
> fix: less margin top on title

- assets/themes/twitter/css/style.css
Hpoefully fixes the remaining issue on horizontal scroll
> fix: wrap title on small screens

- _posts/2018-09-06-angular-performances-part-1.md
Scheduled for Thursday if you can review it before.
It's mainly the content of the ebook, reformated in Markdown,
with an intro and outro.
> post: ng perf series part 1

- _posts/2018-09-18-gradle-kotlin-dsl-documentation.md
- assets/themes/twitter/css/style.css
> post: gradle kotlin DSL contribution

- _posts/2018-09-27-angular-performances-part-4.md
- _posts/2018-10-04-angular-performances-part-5.md
> post: ng perf series part 5

- _posts/2018-09-07-angular-cli-6.2.md
- _posts/2018-10-19-angular-cli-7.0.md
- _posts/2018-11-27-angular-cli-7.1.md
> post: cli 7.1

- _posts/2018-01-07-what-is-new-angular-7.2.md
- _posts/2018-11-22-what-is-new-angular-7.1.md
- _posts/2018-12-21-what-is-new-angular-7.2.md
No rush to review, this is still a WIP
TODO:
> post: ng 7.2

- _posts/2019-02-28-cool-things-we-learned-part-1-backend-edition.md
First draft, what do you think?
I always had a note about `Failure Analyzer` I don't know if it's worth to include it.
> post: cool things we learned backend edition

- _posts/2019-07-03-what-is-new-angular-8.1.md
Not much to say for this release, but I can't really _not_ blog about it now that I have a perfect streak 😛
> post: ng v8.1

- _posts/2019-07-03-angular-cli-8.1.md
> post: cli v8.1

- _posts/2019-09-25-angular-online-training-for-team-discount.md
This is the public announcement of the new feature coded by Cyril. If you approve the message, I'll also plan an email campaign to announce it.
> post: propack discount

- _posts/2020-02-07-angular-cli-9.0.md
> post: cli v9

- _posts/2020-03-26-what-is-new-angular-9.1.md
> post: ng 9.1

- _posts/2021-06-25-angular-cli-12.1.md
- _posts/2021-08-04-angular-cli-12.2.md
- _posts/2021-08-04-what-is-new-angular-12.2.md
> post: ng and cli v12.2

- _posts/2021-09-30-script-setup-syntax-in-vue-3.md
- _posts/2021-09-30-syntaxe-script-setup-en-vue-3 .md
Chapter from the ebook as a blog post
> post: script setup in vue v3.2

- _includes/ninjasquad/trainings
> fix: training certification responsiveness in right navbar

- _posts/2022-02-23-debuter-avec-vite-et-vue.md
- _posts/2022-02-23-getting-started-with-vite-and-vue.md
Both in english and french, adaptations from the ebook chapter `zero-to-something`
> post: getting started with vite and vue 3

- _posts/2023-12-29-what-is-new-vue-3.4.md
> post: vue v3.4

- _posts/2024-05-22-what-is-new-angular-18.0.md
> post: ng v18
